train_ds:
  data_root: "/home/daksh/data/DeSTA2Audio/LibriTTS_R"
  manifest_filepaths:
    - "/home/daksh/data/DeSTA2Audio/LibriTTS_R/debug_train.jsonl"
  batch_sampler: null
  max_seq_length: 300
  batch_size: 2
  shuffle: True
  pin_memory: True
  num_workers: 0
  drop_last: True
  return_seed: False
  answer_shift: 0

validation_ds:
  data_root: "/home/daksh/data/DeSTA2Audio/LibriTTS_R"
  manifest_filepaths:
    - "/home/daksh/data/DeSTA2Audio/LibriTTS_R/debug_val.jsonl"
  batch_sampler: null
  max_seq_length: 512
  batch_size: 1
  shuffle: False
  pin_memory: True
  num_workers: 0
  drop_last: True
  return_seed: False
